### PR TITLE
Deploy automatically using GitHub Actions

### PR DESCRIPTION
**Pull request by imbsky**

### CODE REVIEW

**Comment by weslenng** [comment]
Thanks!

**Comment by imbsky** [comment]
Oh, by the way, don't forget to switch the pages branch to `gh-pages` in repository settings.

**Comment by weslenng** [comment]
Yep, the website rendered README.md for a while 😅
I changed the source of GitHub Pages, probably went back now

**Comment by imbsky** [comment]
Yeah, it seems to be working properly now.

**Comment by imbsky** [comment]
*at least from Japan 🙂

**Pull request merged**
